# Generated by Django 3.1.6 on 2021-03-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectMap',
            new_name='Map',
        ),
    ]
