# Generated by Django 3.1.6 on 2021-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20210325_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sp_playlist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
