# Generated by Django 3.1.6 on 2021-03-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20210326_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
