# Generated by Django 3.1.6 on 2021-03-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_profile_token_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_exp',
            field=models.IntegerField(null=True),
        ),
    ]
