# Generated by Django 3.1.6 on 2021-03-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_profile_token_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_refresh',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
