# Generated by Django 3.1.6 on 2021-04-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20210331_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spotify_refresh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
