# Generated by Django 3.1.6 on 2021-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_auto_20210402_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_refresh',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
